# Generated by Django 3.1.7 on 2022-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('contrib', models.IntegerField()),
                ('is_active', models.BooleanField(verbose_name=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
