# Generated by Django 3.1.7 on 2022-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=100, null=True)),
                ('diet', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('cook_time', models.IntegerField(blank=True, null=True)),
                ('flavour_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('states', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
